GET http://localhost:3600/test?id=2 HTTP/1.1
content-type: application/json


###

GET http://localhost:3600/tests HTTP/1.1
content-type: application/json


###

POST http://localhost:3600/test HTTP/1.1
content-type: application/json

{
    "content": "dsddsds",
    "date" : "2020-06-14",
    "num" : 19,
    "name" : "test2"

}


###

DELETE http://localhost:3600/test?id=2 HTTP/1.1
content-type: application/json


###

PUT http://localhost:3600/test HTTP/1.1
content-type: application/json

{
    "content": "aaaaaa",
    "date" : "2020-06-14",
    "num" : 30,
    "name" : "test2",
    "id" : 2

}

###

GET http://localhost:3600/cdts?groupe=2DE4 HTTP/1.1

###

PUT http://localhost:3600/cdts HTTP/1.1
content-type: application/json

{
    "id" : 1,
    "content": "il y des élèves dans l'école $\\dfrac{3}{4}$"
}

###

GET http://localhost:3600/groupes HTTP/1.1

###

POST http://localhost:3600/cdts HTTP/1.1
content-type: application/json

{
    "content": "",
    "color": "blue",
    "date":"2020-06-12",
    "groupe":"2DE4"
}